name: Integration Tests

on: [push, pull_request]

jobs:
  integration-test:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: integration-tests script
        env:
          IS_GITHUB_ACTIONS: "true"
          SGX_MODE: "SW"
        run: |
          # make file runnable, might not be necessary
          chmod +x "./integration-tests/deploy-snip20.sh"
          chmod +x "./integration-tests/integration.sh"

          // install snip-20 contract
          git clone https://github.com/scrtlabs/snip20-reference-impl

          wget -q https://github.com/scrtlabs/SecretNetwork/releases/download/v1.2.5/secretnetwork_1.2.6vr_rocksdb_amd64.deb
          sudo dpkg -i secret*.deb
          echo installed secretcli with version "$(secretcli version)"
          echo installed on "$(which secretcli)"

          secretcli config chain-id secretdev-1
          secretcli config output json
          secretcli config node http://localhost:26657

          gpg --batch --passphrase '' --quick-gen-key my-gpg-key
          pass init my-gpg-key

          echo sleeping to let node wake up
          sleep 20
          echo sleep completed

          echo "adding keys 'a' and 'b'"
          echo "${{ secrets.A_MNEMONICS }}" | secretcli keys add a --recover
          echo "${{ secrets.B_MNEMONICS }}" | secretcli keys add b --recover
          echo "${{ secrets.C_MNEMONICS }}" | secretcli keys add c --recover
          echo "${{ secrets.D_MNEMONICS }}" | secretcli keys add d --recover

          # run script
          SNIP20_DIR="$(pwd)"/snip20-reference-impl "./integration-tests/deploy-snip20.sh"
          "./integration-tests/integration.sh"
    services:
      secretdev:
        env:
          SECRET_NODE_TYPE: "BOOTSTRAP"
        image: enigmampc/secret-network-sw-dev:v1.2.6
        ports:
          - 26657:26657
          - 5000:5000
          - 1337:1337
